package com.example.nflunkyball.server

import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

class InvitePayloadTest {

    // Generated by the real backend: app/invite_code.py's encode_invite_code(
    //   "https://flunkyball.example.com", "abc123XYZ")
    // Verifies actual cross-language compatibility, not just that Kotlin round-trips itself.
    private val realPythonInviteCode =
        "eyJzZXJ2ZXIiOiAiaHR0cHM6Ly9mbHVua3liYWxsLmV4YW1wbGUuY29tIiwgInRva2VuIjogImFiYzEyM1hZWiJ9"

    @Test
    fun `decodes a real invite code produced by the Python backend`() {
        val decoded = InvitePayloadCodec.decode(realPythonInviteCode)

        assertEquals(InvitePayload(server = "https://flunkyball.example.com", token = "abc123XYZ"), decoded)
    }

    @Test
    fun `decode trims surrounding whitespace`() {
        val decoded = InvitePayloadCodec.decode("  $realPythonInviteCode  \n")

        assertEquals("https://flunkyball.example.com", decoded?.server)
    }

    @Test
    fun `decode rejects garbage input`() {
        assertNull(InvitePayloadCodec.decode("not a valid invite code"))
    }

    @Test
    fun `decode rejects empty input`() {
        assertNull(InvitePayloadCodec.decode(""))
    }
}
